[package]
name = "nihongo"
version = "0.0.0"

[dependencies]
argparse = "0.2"
sdl2 = "0.31"
lazy_static = "1.0"
time = "0.1"

[dependencies.raw-cpuid]
optional = true
git = "https://github.com/gz/rust-cpuid"

[features]
default = ["detect_cpu"]
detect_cpu = ["raw-cpuid"]